log_level: info

behavior:
  read_only: false
  autocommit: true

user:
  name: root
  password: yunti

listener:
  host: 0.0.0.0
  port: 3306
  max_connections: 1000
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000

performance:
  query_parallelism: null
